name: Full-Stack CI Pipeline 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:      # Build Spring Boot backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '19'
      - run: mvn clean package
      - run: mvn test

  frontend:     # Build React frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      # - run: npm test   # Uncomment if you have frontend tests
