name: Full Stack CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/demo
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Backend Tests
        run: mvn test

  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Install Firefox for Selenium
        run: sudo apt-get update && sudo apt-get install firefox -y

      - name: Install geckodriver
        run: |
          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz
          tar -xvzf geckodriver-*.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Run Unit and UI Tests
        run: npm test -- --watchAll=false
